# Generated by Django 4.1.1 on 2023-09-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/category_images/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_url', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/club_images/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_media_partner', 'Is Media Partner?')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.BigIntegerField(blank=True, null=True)),
                ('income_amount', models.BigIntegerField()),
                ('is_collected', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.'), ('Prof', 'Prof.'), ('Lion', 'Lion'), ('Adv', 'Adv'), ('CA', 'CA'), ('Er', 'Er'), ('Rtn', 'Rtn'), ('Vn', 'Vn')], max_length=10, null=True)),
                ('altname', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('detailType', models.CharField(default='F', max_length=2)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('door_no', models.CharField(blank=True, max_length=50, null=True)),
                ('building_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=7, verbose_name='Pincode')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('std_code', models.CharField(blank=True, max_length=5, null=True)),
                ('landline', models.CharField(blank=True, max_length=11, null=True)),
                ('logo', django_resized.forms.ResizedImageField(crop=None, default='webimages/cel.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/logo/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(blank=True, choices=[('Branch Office', 'Branch Office'), ('Consultant', 'Consultant'), ('Dealer', 'Dealer'), ('Dealer', 'Dealer'), ('Exporter', 'Exporter'), ('Franchises', 'Franchises'), ('Head Office', 'Head Office'), ('Industry', 'Industry'), ('MicroIndustry', 'MicroIndustry'), ('Office', 'Office'), ('Professional', 'Professional'), ('Service Firm', 'Service Firm'), ('Shop', 'Shop'), ('SSI', 'SSI'), ('Tiny Industry', 'Tiny Industry'), ('Wholesaler', 'Wholesaler')], default='Shop', max_length=100, null=True)),
                ('firm_type', models.CharField(blank=True, choices=[('M', 'Manufacturer'), ('D', 'Dealer'), ('S', 'Service')], default='Suppliers', max_length=20, null=True)),
                ('mtype1', models.CharField(choices=[('M', 'Manufacturer'), ('D', 'Dealer'), ('S', 'Service')], default='Service', max_length=100)),
                ('mtype2', models.CharField(choices=[('M', 'Manufacturer'), ('D', 'Dealer'), ('S', 'Service')], default='Service', max_length=100)),
                ('mtype3', models.CharField(choices=[('M', 'Manufacturer'), ('D', 'Dealer'), ('S', 'Service')], default='Service', max_length=100)),
                ('visiting_card', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/visitingcard/')),
                ('blood_donor', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('martial_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50, null=True)),
                ('education', models.CharField(blank=True, choices=[('Post Gratuate', 'Post Gratuate'), ('Graduate', 'Graduate'), ('High School', 'High School'), ('School', 'School'), ('No School', 'No School')], max_length=50, null=True)),
                ('employment', models.CharField(blank=True, choices=[('Govt. Employed', 'Govt. Employed'), ('Govt.Undertakings Employed', 'Govt.Undertakings Employed'), ('Private Firm Employed', 'Private Firm Employed'), ('Self Employed', 'Self Employed'), ('Free Lancer - Part Time', 'Free Lancer - Part Time'), ('Retired Sr.Citizen', 'Retired Sr.Citizen'), ('Un Employed', 'Un Employed')], max_length=50, null=True)),
                ('responsibility', models.CharField(blank=True, choices=[('Head of Family', 'Head of Family'), ('House Wife', 'House Wife'), ('Student', 'Student'), ('Senior Citizen', 'Senior Citizen')], max_length=50, null=True)),
                ('income', models.CharField(blank=True, choices=[('Affluent', 'Affluent'), ('Higher Income', 'Higher Income'), ('Middle Income', 'Middle Income'), ('Lower Income', 'Lower Income')], max_length=50, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('colour_advertisement', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/advertisement/')),
                ('business_listing', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/colour_advertisement/')),
                ('video', models.CharField(blank=True, max_length=200, null=True)),
                ('catalogue', models.FileField(blank=True, null=True, upload_to='webimages/catalog/')),
                ('agree', models.BooleanField(blank=True, default=True)),
                ('shop_created_at', models.DateTimeField(auto_now_add=True)),
                ('club_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.clubs')),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion')),
                ('listing_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to=settings.AUTH_USER_MODEL)),
                ('mcategory1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc1', to='base.category')),
                ('mcategory2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc2', to='base.category')),
                ('mcategory3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc3', to='base.category')),
                ('mproducts1', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp1', to='base.product')),
                ('mproducts2', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp2', to='base.product')),
                ('mproducts3', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp3', to='base.product')),
                ('msub_category1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msc1', to='base.sub_category')),
                ('msub_category2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msc2', to='base.sub_category')),
                ('msub_category3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msc3', to='base.sub_category')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_wishlist', models.ManyToManyField(blank=True, null=True, related_name='users_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'firm',
                'verbose_name_plural': 'firms',
                'ordering': ['-listing_type'],
            },
        ),
        migrations.CreateModel(
            name='WorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('firm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.task')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='base.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bl_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.businesslistingincome')),
                ('data_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.income')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.sub_category'),
        ),
        migrations.CreateModel(
            name='IndividualTotalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.BigIntegerField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('total_fields', models.IntegerField(blank=True, null=True)),
                ('income', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcomProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=60, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_descriptions', models.TextField(blank=True, max_length=300, null=True)),
                ('product_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/ecom_products/')),
                ('firm_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.task')),
            ],
        ),
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/user-profiles/')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Firm', 'Firm'), ('Person', 'Person')], default='Person', max_length=25)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('credit_points', models.BigIntegerField(default=100)),
                ('minimum_points', models.BigIntegerField(default=9)),
                ('account_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessListingIncomeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/business_listing/')),
                ('space_code', models.CharField(blank=True, max_length=50, null=True)),
                ('space_value', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('GPay', 'GPay'), ('NEFT', 'NEFT'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online'), ('AFTER PROOF APPROVAL', 'After Proof Approval')], default='ONLINE', max_length=20)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('firm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
