# Generated by Django 4.1.1 on 2023-11-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subscriptions_task_search_count_task_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='individualincome',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualtotalincome',
            name='total_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
