# Generated by Django 4.1.1 on 2023-11-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_income_income_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksummary',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
