# Generated by Django 4.1.1 on 2023-11-15 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_businesslisting_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pink_pg_title', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('door_street', models.CharField(blank=True, max_length=100, null=True)),
                ('city_pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('landline', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True)),
                ('whatsapp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('name_desg1', models.CharField(blank=True, max_length=100, null=True)),
                ('number1', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name_desg2', models.CharField(blank=True, max_length=100, null=True)),
                ('number2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name_desg3', models.CharField(blank=True, max_length=100, null=True)),
                ('number3', models.PositiveBigIntegerField(blank=True, null=True)),
                ('activity1', models.CharField(blank=True, max_length=100, null=True)),
                ('activity2', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
