# Generated by Django 4.1.1 on 2023-11-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='activity1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='activity2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
