# Generated by Django 4.1.1 on 2023-11-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_advertisement_activity1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
