# Generated by Django 4.1.1 on 2023-11-30 05:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='webimages/logo/'),
        ),
    ]
