# Generated by Django 4.1.1 on 2023-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_task_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='nature',
            field=models.CharField(blank=True, choices=[('Branch Office', 'Branch Office'), ('Consultant', 'Consultant'), ('Dealer', 'Dealer'), ('Dealer', 'Dealer'), ('Exporter', 'Exporter'), ('Franchises', 'Franchises'), ('Head Office', 'Head Office'), ('Industry', 'Industry'), ('MicroIndustry', 'MicroIndustry'), ('Office', 'Office'), ('Professional', 'Professional'), ('Service Firm', 'Service Firm'), ('Shop', 'Shop'), ('SSI', 'SSI'), ('Tiny Industry', 'Tiny Industry'), ('Wholesaler', 'Wholesaler')], max_length=100, null=True),
        ),
    ]
