# Generated by Django 4.1.1 on 2023-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('education', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('preference', models.CharField(blank=True, max_length=1000, null=True)),
                ('package', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creditvalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.IntegerField(default=2)),
                ('email', models.IntegerField(default=2)),
                ('whatsapp', models.IntegerField(default=2)),
                ('bulk_sms', models.IntegerField(default=5)),
                ('bulk_email', models.IntegerField(default=5)),
                ('bulk_whatsapp', models.IntegerField(default=5)),
                ('download', models.IntegerField(default=2)),
            ],
        ),
    ]
