# Generated by Django 4.1.1 on 2023-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='desc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
