# Generated by Django 4.1.1 on 2023-12-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_faqsub_faqs_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.faqsub'),
        ),
    ]
